id: theia-theme-plugin
version: 1.0.0
type: Theia plugin
name: Theia theme plugin
title: Theia theme plugin
description: Theia plugin that changes the theme
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
url: https://github.com/levjason/theia-theme-plugin/blob/master/theia_theme_plugin.theia?raw=true
publisher: Jason
category: Other
firstPublicationDate: "2019-04-08"